[tool.poetry]
name = "pricingengine"
version = "0.1.0"
description = ""
authors = ["Senpher <crazykronecker@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
quantlib = "^1.39"
pandas = "^2.3.2"
ruff = "==0.13.0"
poetry-core = "^2.2.0"
pandas-stubs = "==2.3.2.250827"
pytest = "^8.4.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "ruff==0.13.0"
]

[tool.pytest.ini_options]
pythonpath = [
    "."
]
