"""Compatibility layer exposing the portfolio engine under the legacy name."""

from portfolioengine import (
    IRS,
    ClientPosition,
    EquityOption,
    FXForward,
    FXOption,
    Repo,
    computation,
    compute,
    compute_instrument,
    compute_portfolio,
    factor_utils,
    get_engine_class,
    get_engine_metric_function,
    get_factors,
    get_instrument_class,
    get_metric_function,
    instrument_registry,
    portfolio_engine_registry,
)

__all__ = [
    "ClientPosition",
    "EquityOption",
    "FXForward",
    "FXOption",
    "IRS",
    "Repo",
    "computation",
    "compute",
    "compute_instrument",
    "compute_portfolio",
    "factor_utils",
    "get_engine_class",
    "get_engine_metric_function",
    "get_factors",
    "get_instrument_class",
    "get_metric_function",
    "instrument_registry",
    "portfolio_engine_registry",
]
