name: CI

on:
  push:
  pull_request:
  workflow_dispatch: {}

jobs:
  check:
    name: CI - check
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v1
      - name: Install deps
        run: uv sync
      - name: Ruff
        run: uv run ruff check .
      - name: Black (check)
        run: uv run black --check .
      - name: Mypy
        run: uv run mypy src
      - name: Pytest
        run: uv run pytest -q --junitxml=pytest-report.xml
      - name: Upload pytest report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-report
          path: pytest-report.xml
